import { drawPdfInlineText, hasInlineMarkdown } from "@/lib/inlineMarkdown";
import {
    extractEditableTables,
    groupLinesForDisplay,
    isBulletLine,
    parseProposalContent,
    stripBulletPrefix,
    type DisplaySegment,
} from "@/lib/proposalContentMarkdown";
import {
    LETTER_SIGNATORY,
    formatLetterDateLong,
    formatLetterPhone,
    letterSalutation,
    normalizeLetterContent,
} from "@/lib/letterDocument";
import type { Letter } from "@/lib/letterUi";

const COMPANY = {
    name: "VIROS ENTREPRENEURS",
    subtitle: "IT Solutions Private Limited",
    tagline1: "Deals In Complete Software and Hardware Solutions",
    tagline2: "We Provide Complete Industrial Solutions",
    address:
        "25/2, Street -2, 1st Floor, Molarband Market, Beside Om TVS bike Showroom, Badarpur, New Delhi INDIA, Delhi - 110044",
    email: "sales@virosentrepreneurs.com",
    phone: "9871029141",
    website: "www.virosentrepreneurs.com",
};

const PAGE_MARGIN = 14;
const PRIMARY: [number, number, number] = [6, 18, 79];
const ACCENT: [number, number, number] = [6, 182, 212];
const SECONDARY: [number, number, number] = [10, 42, 94];
const BORDER = 200;
const FOOTER_RESERVED = 28;
const TEXT_COLOR: [number, number, number] = [30, 30, 30];
const MUTED_COLOR: [number, number, number] = [120, 120, 120];

const LOGO_PATH = "/payslip-logo.png";

type PdfDoc = import("jspdf").jsPDF;

type LogoAsset = {
    dataUrl: string;
    format: "PNG" | "JPEG";
    widthPx: number;
    heightPx: number;
};

function getPageWidth(doc: PdfDoc): number {
    return doc.internal.pageSize.getWidth();
}

function getPageHeight(doc: PdfDoc): number {
    return doc.internal.pageSize.getHeight();
}

function stripInlineMarkdown(text: string): string {
    return text
        .replace(/\*\*(.+?)\*\*/g, "$1")
        .replace(/\*(.+?)\*/g, "$1")
        .replace(/`(.+?)`/g, "$1")
        .trim();
}

async function loadLogoAsset(): Promise<LogoAsset | null> {
    if (typeof window === "undefined") return null;

    const logoUrl = `${window.location.origin}${LOGO_PATH}?v=1`;
    try {
        const resp = await fetch(logoUrl, { cache: "no-store" });
        if (!resp.ok) return null;

        const blob = await resp.blob();
        const dataUrl = await new Promise<string | null>((resolve) => {
            const reader = new FileReader();
            reader.onloadend = () => resolve(typeof reader.result === "string" ? reader.result : null);
            reader.onerror = () => resolve(null);
            reader.readAsDataURL(blob);
        });
        if (!dataUrl) return null;

        const format: LogoAsset["format"] = blob.type.includes("jpeg") ? "JPEG" : "PNG";
        const dimensions = await new Promise<{ width: number; height: number } | null>((resolve) => {
            const img = new Image();
            img.onload = () =>
                resolve({ width: img.naturalWidth || 1, height: img.naturalHeight || 1 });
            img.onerror = () => resolve(null);
            img.src = dataUrl;
        });
        if (!dimensions) return null;

        return { dataUrl, format, widthPx: dimensions.width, heightPx: dimensions.height };
    } catch {
        return null;
    }
}

function drawHr(doc: PdfDoc, y: number): number {
    const pageWidth = getPageWidth(doc);
    doc.setDrawColor(BORDER, BORDER, BORDER);
    doc.setLineWidth(0.3);
    doc.line(PAGE_MARGIN, y, pageWidth - PAGE_MARGIN, y);
    return y;
}

function ensureSpace(doc: PdfDoc, y: number, needed: number): number {
    const pageHeight = getPageHeight(doc);
    if (y + needed <= pageHeight - FOOTER_RESERVED) return y;
    doc.addPage();
    return PAGE_MARGIN + 4;
}

function drawPageFooter(doc: PdfDoc, pageNum: number, totalPages: number): void {
    const pageWidth = getPageWidth(doc);
    const pageHeight = getPageHeight(doc);
    const y = pageHeight - 18;

    drawHr(doc, y - 4);

    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(...ACCENT);
    doc.text("*** This letter is generated by the system ***", pageWidth / 2, y, { align: "center" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(120, 120, 120);
    doc.text(
        `For any queries, contact us at ${COMPANY.email} | ${COMPANY.phone}`,
        pageWidth / 2,
        y + 4,
        { align: "center" },
    );

    doc.setFontSize(8);
    doc.setTextColor(80, 80, 80);
    doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth / 2, y + 9, { align: "center" });
}

function drawHeader(doc: PdfDoc, logo: LogoAsset | null): number {
    const pageWidth = getPageWidth(doc);
    let textX = PAGE_MARGIN;

    if (logo) {
        const maxH = 14;
        const aspect = logo.widthPx / logo.heightPx;
        let drawH = maxH;
        let drawW = drawH * aspect;
        if (drawW > 18) {
            drawW = 18;
            drawH = drawW / aspect;
        }
        doc.addImage(logo.dataUrl, logo.format, PAGE_MARGIN, 10, drawW, drawH);
        textX = PAGE_MARGIN + drawW + 4;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...PRIMARY);
    doc.text(COMPANY.name, textX, 15);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...SECONDARY);
    doc.text(COMPANY.subtitle, textX, 20);

    doc.setFontSize(7.5);
    doc.setTextColor(...ACCENT);
    doc.text(COMPANY.tagline1, textX, 25);
    doc.text(COMPANY.tagline2, textX, 29);

    const rightX = pageWidth - PAGE_MARGIN;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(80, 80, 80);

    const contactLines = [
        `Address: ${COMPANY.address}`,
        `Email: ${COMPANY.email}`,
        `Contact: ${COMPANY.phone}`,
        `Website: ${COMPANY.website}`,
    ];

    let contactY = 12;
    for (const line of contactLines) {
        const wrapped = doc.splitTextToSize(line, 72);
        doc.text(wrapped, rightX, contactY, { align: "right" });
        contactY += wrapped.length * 3.2;
    }

    drawHr(doc, 36);
    return 42;
}

const LINE_HEIGHT = 6;
const PARA_GAP = 3;

function contentHasMarkdownTable(content: string): boolean {
    return extractEditableTables(content).length > 0;
}

/** Renders letter body using only the line breaks present in the source text. */
function drawLetterBodyContent(doc: PdfDoc, y: number, content: string): number {
    const contentWidth = getPageWidth(doc) - PAGE_MARGIN * 2;
    const lines = content.replace(/\r\n/g, "\n").split("\n");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...TEXT_COLOR);

    for (const line of lines) {
        const trimmed = line.trim();

        if (!trimmed) {
            y = ensureSpace(doc, y, LINE_HEIGHT);
            y += LINE_HEIGHT;
            continue;
        }

        if (trimmed.startsWith("## ")) {
            const title = trimmed.slice(3).trim();
            y = ensureSpace(doc, y, LINE_HEIGHT);
            doc.setFontSize(10);
            doc.setTextColor(...PRIMARY);
            y = drawPdfInlineText(doc, PAGE_MARGIN, y, contentWidth, title, LINE_HEIGHT, {
                baseBold: true,
            });
            doc.setFont("helvetica", "normal");
            doc.setFontSize(10);
            doc.setTextColor(...TEXT_COLOR);
            continue;
        }

        if (isBulletLine(line)) {
            const bulletText = stripBulletPrefix(line);
            const textX = PAGE_MARGIN + 8;
            const textWidth = contentWidth - 8;
            y = ensureSpace(doc, y, LINE_HEIGHT);
            doc.setFont("helvetica", "bold");
            doc.setTextColor(...TEXT_COLOR);
            doc.text("•", PAGE_MARGIN + 2, y);
            doc.setFont("helvetica", "normal");
            if (hasInlineMarkdown(bulletText)) {
                y = drawPdfInlineText(doc, textX, y, textWidth, bulletText, LINE_HEIGHT);
            } else {
                const wrapped = doc.splitTextToSize(bulletText, textWidth);
                doc.text(wrapped, textX, y);
                y += wrapped.length * LINE_HEIGHT;
            }
            continue;
        }

        if (hasInlineMarkdown(line)) {
            y = ensureSpace(doc, y, LINE_HEIGHT);
            y = drawPdfInlineText(doc, PAGE_MARGIN, y, contentWidth, line, LINE_HEIGHT);
            continue;
        }

        const wrapped = doc.splitTextToSize(line, contentWidth);
        y = ensureSpace(doc, y, wrapped.length * LINE_HEIGHT);
        doc.setFont("helvetica", "normal");
        doc.text(line, PAGE_MARGIN, y, { maxWidth: contentWidth, align: "justify" });
        y += wrapped.length * LINE_HEIGHT;
    }

    return y;
}

function drawJustifiedText(doc: PdfDoc, y: number, text: string): number {
    const contentWidth = getPageWidth(doc) - PAGE_MARGIN * 2;
    const paragraphs = text
        .split(/\n+/)
        .map((part) => stripInlineMarkdown(part))
        .filter((part) => part.trim());

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...TEXT_COLOR);

    for (const paragraph of paragraphs) {
        const wrapped = doc.splitTextToSize(paragraph, contentWidth);
        y = ensureSpace(doc, y, wrapped.length * LINE_HEIGHT + PARA_GAP);
        doc.text(paragraph, PAGE_MARGIN, y, { maxWidth: contentWidth, align: "justify" });
        y += wrapped.length * LINE_HEIGHT + PARA_GAP;
    }

    return y;
}

function drawBulletList(doc: PdfDoc, y: number, items: string[]): number {
    const pageWidth = getPageWidth(doc);
    const bulletX = PAGE_MARGIN + 2;
    const textX = PAGE_MARGIN + 8;
    const textWidth = pageWidth - textX - PAGE_MARGIN;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...TEXT_COLOR);

    for (const item of items) {
        const text = stripInlineMarkdown(item);
        const wrapped = doc.splitTextToSize(text, textWidth);
        y = ensureSpace(doc, y, wrapped.length * LINE_HEIGHT + 3);
        doc.setFont("helvetica", "bold");
        doc.text("•", bulletX, y);
        doc.setFont("helvetica", "normal");
        doc.text(wrapped, textX, y);
        y += wrapped.length * LINE_HEIGHT + 3;
    }

    return y + 2;
}

function drawDisplaySegments(doc: PdfDoc, y: number, segments: DisplaySegment[]): number {
    for (const segment of segments) {
        if (segment.type === "list") {
            y = drawBulletList(doc, y, segment.items);
            continue;
        }

        const text = segment.lines.map(stripInlineMarkdown).join("\n");
        y = drawJustifiedText(doc, y, text);
    }

    return y;
}

function renderContentBlocks(
    doc: PdfDoc,
    autoTable: typeof import("jspdf-autotable").default,
    y: number,
    content: string,
): number {
    const blocks = parseProposalContent(content);
    if (blocks.length === 0) return y;

    for (const block of blocks) {
        if (block.type === "heading") {
            doc.setFont("helvetica", "bold");
            doc.setFontSize(10);
            doc.setTextColor(...PRIMARY);
            const title = stripInlineMarkdown(block.title);
            y = ensureSpace(doc, y, 10);
            doc.text(title, PAGE_MARGIN, y);
            y += 6;

            if (block.lines.length > 0) {
                y = drawDisplaySegments(doc, y, groupLinesForDisplay(block.lines));
            }
            continue;
        }

        if (block.type === "list") {
            y = drawBulletList(doc, y, block.items);
            continue;
        }

        if (block.type === "paragraph") {
            y = drawDisplaySegments(doc, y, groupLinesForDisplay(block.lines));
            continue;
        }

        if (block.type === "table") {
            y = ensureSpace(doc, y, 20);
            autoTable(doc, {
                startY: y,
                head: [block.header.map(stripInlineMarkdown)],
                body: block.rows.map((row) => row.map(stripInlineMarkdown)),
                theme: "grid",
                styles: {
                    fontSize: 9,
                    cellPadding: 2,
                    textColor: TEXT_COLOR,
                    lineColor: [BORDER, BORDER, BORDER],
                    lineWidth: 0.2,
                },
                headStyles: {
                    fillColor: PRIMARY,
                    textColor: [255, 255, 255],
                    fontStyle: "bold",
                },
                margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
            });
            const lastTable = (doc as PdfDoc & { lastAutoTable?: { finalY: number } }).lastAutoTable;
            y = (lastTable?.finalY ?? y) + 6;
        }
    }

    return y;
}

function drawSubjectLine(doc: PdfDoc, y: number, subject: string): number {
    const pageWidth = getPageWidth(doc);
    const contentWidth = pageWidth - PAGE_MARGIN * 2;
    const label = "Subject:";
    const gap = 1.5;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...TEXT_COLOR);
    const labelWidth = doc.getTextWidth(`${label} `);
    const firstLineWidth = contentWidth - labelWidth - gap;
    const wrapped = doc.splitTextToSize(subject, firstLineWidth);

    y = ensureSpace(doc, y, wrapped.length * LINE_HEIGHT + 4);
    doc.text(`${label} `, PAGE_MARGIN, y);

    doc.setFont("helvetica", "normal");
    if (wrapped.length <= 1) {
        doc.text(subject, PAGE_MARGIN + labelWidth + gap, y);
        return y + LINE_HEIGHT + 6;
    }

    doc.text(wrapped[0], PAGE_MARGIN + labelWidth + gap, y);
    y += LINE_HEIGHT;
    for (let i = 1; i < wrapped.length; i += 1) {
        y = ensureSpace(doc, y, LINE_HEIGHT);
        doc.text(wrapped[i], PAGE_MARGIN, y);
        y += LINE_HEIGHT;
    }

    return y + 6;
}

function drawFormalLetterBody(doc: PdfDoc, y: number, letter: Letter): number {
    const pageWidth = getPageWidth(doc);
    const rightX = pageWidth - PAGE_MARGIN;
    const phone = letter.clientPhone.trim() ? formatLetterPhone(letter.clientPhone) : "";

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...TEXT_COLOR);
    doc.text(`Ref: ${letter.letterNumber}`, PAGE_MARGIN, y);
    doc.text(`Date: ${formatLetterDateLong(letter.letterDate)}`, rightX, y, { align: "right" });
    y += 12;

    doc.setFont("helvetica", "bold");
    doc.text("To,", PAGE_MARGIN, y);
    y += 6;
    doc.text(letter.clientName, PAGE_MARGIN, y);
    y += 6;

    doc.setFont("helvetica", "normal");
    if (letter.designation.trim()) {
        doc.text(letter.designation, PAGE_MARGIN, y);
        y += 6;
    }

    if (letter.clientContact.trim() && letter.clientContact.trim() !== letter.clientName.trim()) {
        doc.text(letter.clientContact, PAGE_MARGIN, y);
        y += 6;
    }
    if (letter.clientEmail.trim()) {
        doc.setTextColor(...MUTED_COLOR);
        doc.text(`Email: ${letter.clientEmail}`, PAGE_MARGIN, y);
        doc.setTextColor(...TEXT_COLOR);
        y += 6;
    }
    if (phone) {
        doc.setTextColor(...MUTED_COLOR);
        doc.text(`Contact: ${phone}`, PAGE_MARGIN, y);
        doc.setTextColor(...TEXT_COLOR);
        y += 6;
    }

    y += 4;
    y = drawSubjectLine(doc, y, letter.subject);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...TEXT_COLOR);
    doc.text(letterSalutation(letter), PAGE_MARGIN, y);
    return y + 6;
}

function drawSignatureBlock(doc: PdfDoc, y: number): number {
    y = ensureSpace(doc, y, 40);
    const rightX = getPageWidth(doc) - PAGE_MARGIN;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...TEXT_COLOR);
    doc.text("Sincerely,", rightX, y, { align: "right" });
    y += 22;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    doc.text(LETTER_SIGNATORY.title, rightX, y, { align: "right" });
    y += 5;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...TEXT_COLOR);
    doc.text(LETTER_SIGNATORY.company, rightX, y, { align: "right" });
    y += 5;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text(LETTER_SIGNATORY.subtitle, rightX, y, { align: "right" });

    return y + 6;
}

export async function downloadLetterPdf(letter: Letter): Promise<void> {
    const [{ jsPDF }, autoTableModule, logo] = await Promise.all([
        import("jspdf"),
        import("jspdf-autotable"),
        loadLogoAsset(),
    ]);
    const autoTable = autoTableModule.default;
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

    let y = drawHeader(doc, logo);
    y = drawFormalLetterBody(doc, y, letter);

    const bodyContent = normalizeLetterContent(letter.content, letter);
    if (bodyContent) {
        y = contentHasMarkdownTable(bodyContent)
            ? renderContentBlocks(doc, autoTable, y, bodyContent)
            : drawLetterBodyContent(doc, y, bodyContent);
    }

    y = drawSignatureBlock(doc, y);

    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        drawPageFooter(doc, i, totalPages);
    }

    const safeName = letter.letterNumber.replace(/[^\w-]+/g, "_");
    doc.save(`Letter-${safeName}.pdf`);
}
