import {
    groupLinesForDisplay,
    parseProposalContent,
    type ContentBlock,
    type DisplaySegment,
} from "@/lib/proposalContentMarkdown";
import { formatProposalDate, type Proposal } from "@/lib/proposalUi";

const COMPANY = {
    name: "VIROS ENTREPRENEURS",
    subtitle: "IT Solutions Private Limited",
    tagline1: "Deals In Complete Software and Hardware Solutions",
    tagline2: "We Provide Complete Industrial Solutions",
    address:
        "25/2, Street -2, 1st Floor, Molarband Market, Beside Om TVS bike Showroom, Badarpur, New Delhi INDIA, Delhi - 110044",
    email: "sales@virosentrepreneurs.com",
    phone: "9871029141",
    website: "www.virosentrepreneurs.com",
};

const PAGE_MARGIN = 14;
const PRIMARY: [number, number, number] = [6, 18, 79];
const ACCENT: [number, number, number] = [6, 182, 212];
const SECONDARY: [number, number, number] = [10, 42, 94];
const PANEL_FILL: [number, number, number] = [248, 250, 252];
const HIGHLIGHT_FILL: [number, number, number] = [236, 254, 255];
const BORDER = 200;
const FOOTER_RESERVED = 28;

const LOGO_PATH = "/payslip-logo.png";

type PdfDoc = import("jspdf").jsPDF;

type LogoAsset = {
    dataUrl: string;
    format: "PNG" | "JPEG";
    widthPx: number;
    heightPx: number;
};

function getPageWidth(doc: PdfDoc): number {
    return doc.internal.pageSize.getWidth();
}

function getPageHeight(doc: PdfDoc): number {
    return doc.internal.pageSize.getHeight();
}

function stripInlineMarkdown(text: string): string {
    return text
        .replace(/\*\*(.+?)\*\*/g, "$1")
        .replace(/\*(.+?)\*/g, "$1")
        .replace(/`(.+?)`/g, "$1")
        .trim();
}

function formatPdfDate(iso: string | null): string {
    if (!iso) return "—";
    const d = new Date(iso.includes("T") ? iso : `${iso}T12:00:00`);
    if (Number.isNaN(d.getTime())) return iso;
    return d.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
}

/** PDF-safe currency — Helvetica does not render the rupee sign (₹) correctly. */
function formatPdfAmount(amount: number): string {
    const n = Number.isFinite(amount) ? amount : 0;
    const hasDecimals = Math.round(n * 100) % 100 !== 0;
    const formatted = new Intl.NumberFormat("en-IN", {
        minimumFractionDigits: hasDecimals ? 2 : 0,
        maximumFractionDigits: 2,
    }).format(n);
    return `Rs. ${formatted}`;
}

function formatPhone(phone: string): string {
    const digits = phone.replace(/\D/g, "");
    if (digits.length === 10) return `+91 ${digits}`;
    if (digits.length === 12 && digits.startsWith("91")) return `+91 ${digits.slice(2)}`;
    return phone.trim() || "—";
}

async function loadLogoAsset(): Promise<LogoAsset | null> {
    if (typeof window === "undefined") return null;

    const logoUrl = `${window.location.origin}${LOGO_PATH}?v=1`;
    try {
        const resp = await fetch(logoUrl, { cache: "no-store" });
        if (!resp.ok) return null;

        const blob = await resp.blob();
        const dataUrl = await new Promise<string | null>((resolve) => {
            const reader = new FileReader();
            reader.onloadend = () => resolve(typeof reader.result === "string" ? reader.result : null);
            reader.onerror = () => resolve(null);
            reader.readAsDataURL(blob);
        });
        if (!dataUrl) return null;

        const format: LogoAsset["format"] = blob.type.includes("jpeg") ? "JPEG" : "PNG";
        const dimensions = await new Promise<{ width: number; height: number } | null>((resolve) => {
            const img = new Image();
            img.onload = () =>
                resolve({ width: img.naturalWidth || 1, height: img.naturalHeight || 1 });
            img.onerror = () => resolve(null);
            img.src = dataUrl;
        });
        if (!dimensions) return null;

        return { dataUrl, format, widthPx: dimensions.width, heightPx: dimensions.height };
    } catch {
        return null;
    }
}

function drawHr(doc: PdfDoc, y: number): number {
    const pageWidth = getPageWidth(doc);
    doc.setDrawColor(BORDER, BORDER, BORDER);
    doc.setLineWidth(0.3);
    doc.line(PAGE_MARGIN, y, pageWidth - PAGE_MARGIN, y);
    return y;
}

function ensureSpace(doc: PdfDoc, y: number, needed: number): number {
    const pageHeight = getPageHeight(doc);
    if (y + needed <= pageHeight - FOOTER_RESERVED) return y;
    doc.addPage();
    return PAGE_MARGIN + 4;
}

function drawPageFooter(doc: PdfDoc, pageNum: number, totalPages: number): void {
    const pageWidth = getPageWidth(doc);
    const pageHeight = getPageHeight(doc);
    const y = pageHeight - 18;

    drawHr(doc, y - 4);

    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(...ACCENT);
    doc.text("*** This proposal is generated by the system ***", pageWidth / 2, y, { align: "center" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(120, 120, 120);
    doc.text(
        `For any queries, contact us at ${COMPANY.email} | ${COMPANY.phone}`,
        pageWidth / 2,
        y + 4,
        { align: "center" },
    );

    doc.setFontSize(8);
    doc.setTextColor(80, 80, 80);
    doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth / 2, y + 9, { align: "center" });
}

function drawHeader(doc: PdfDoc, logo: LogoAsset | null): number {
    const pageWidth = getPageWidth(doc);
    let textX = PAGE_MARGIN;

    if (logo) {
        const maxH = 14;
        const aspect = logo.widthPx / logo.heightPx;
        let drawH = maxH;
        let drawW = drawH * aspect;
        if (drawW > 18) {
            drawW = 18;
            drawH = drawW / aspect;
        }
        doc.addImage(logo.dataUrl, logo.format, PAGE_MARGIN, 10, drawW, drawH);
        textX = PAGE_MARGIN + drawW + 4;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...PRIMARY);
    doc.text(COMPANY.name, textX, 15);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...SECONDARY);
    doc.text(COMPANY.subtitle, textX, 20);

    doc.setFontSize(7.5);
    doc.setTextColor(...ACCENT);
    doc.text(COMPANY.tagline1, textX, 25);
    doc.text(COMPANY.tagline2, textX, 29);

    const rightX = pageWidth - PAGE_MARGIN;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(80, 80, 80);

    const contactLines = [
        `Address: ${COMPANY.address}`,
        `Email: ${COMPANY.email}`,
        `Contact: ${COMPANY.phone}`,
        `Website: ${COMPANY.website}`,
    ];

    let contactY = 12;
    for (const line of contactLines) {
        const wrapped = doc.splitTextToSize(line, 72);
        doc.text(wrapped, rightX, contactY, { align: "right" });
        contactY += wrapped.length * 3.2;
    }

    drawHr(doc, 36);
    return 42;
}

function drawTitleBand(doc: PdfDoc, y: number, projectTitle: string): number {
    const pageWidth = getPageWidth(doc);
    const centerX = pageWidth / 2;
    const bandTop = y;
    const bandHeight = 16;

    doc.setDrawColor(...PRIMARY);
    doc.setLineWidth(0.4);
    doc.rect(PAGE_MARGIN, bandTop, pageWidth - PAGE_MARGIN * 2, bandHeight);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(...PRIMARY);
    doc.text("BUSINESS PROPOSAL / PROJECT SCOPE", centerX, bandTop + 7, { align: "center" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...ACCENT);
    doc.text(projectTitle, centerX, bandTop + 13, { align: "center" });

    return bandTop + bandHeight + 6;
}

type PanelRow = { label: string; value: string; highlight?: boolean };

function measurePanelHeight(doc: PdfDoc, rows: PanelRow[], width: number): number {
    let h = 14;
    for (const row of rows) {
        const valueLines = doc.splitTextToSize(row.value || "—", width - 38);
        h += Math.max(5, valueLines.length * 3.8);
    }
    return h + 4;
}

function drawInfoPanel(
    doc: PdfDoc,
    x: number,
    y: number,
    width: number,
    title: string,
    rows: PanelRow[],
    fixedHeight?: number,
): number {
    const panelH = fixedHeight ?? measurePanelHeight(doc, rows, width);

    doc.setFillColor(...PANEL_FILL);
    doc.setDrawColor(BORDER, BORDER, BORDER);
    doc.setLineWidth(0.2);
    doc.rect(x, y, width, panelH, "FD");

    doc.setFillColor(...ACCENT);
    doc.rect(x, y, 2.5, panelH, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(...PRIMARY);
    doc.text(title, x + 5, y + 6);

    let rowY = y + 12;
    doc.setFontSize(7.5);

    for (const row of rows) {
        doc.setFont("helvetica", "bold");
        doc.setTextColor(90, 90, 90);
        doc.text(`${row.label}:`, x + 5, rowY);

        doc.setFont("helvetica", "normal");
        if (row.highlight) {
            doc.setTextColor(...ACCENT);
        } else {
            doc.setTextColor(40, 40, 40);
        }

        const valueLines = doc.splitTextToSize(row.value || "—", width - 38);
        doc.text(valueLines, x + 32, rowY);
        rowY += Math.max(5, valueLines.length * 3.8);
    }

    return y + panelH;
}

function drawDualInfoPanels(doc: PdfDoc, y: number, proposal: Proposal): number {
    const pageWidth = getPageWidth(doc);
    const gap = 4;
    const colW = (pageWidth - PAGE_MARGIN * 2 - gap) / 2;
    const leftX = PAGE_MARGIN;
    const rightX = PAGE_MARGIN + colW + gap;

    const clientRows: PanelRow[] = [
        { label: "Company / Firm", value: proposal.clientName },
        { label: "Contact Person", value: proposal.clientContact || "—" },
        { label: "Email", value: proposal.clientEmail || "—" },
        { label: "Phone", value: formatPhone(proposal.clientPhone) },
    ];

    const proposalRows: PanelRow[] = [
        { label: "Proposal ID", value: proposal.proposalNumber, highlight: true },
        { label: "Date", value: formatPdfDate(proposal.createdAt) },
        { label: "Valid Until", value: formatProposalDate(proposal.validUntil) },
        {
            label: "Proposed Amount",
            value: proposal.proposedAmount > 0 ? formatPdfAmount(proposal.proposedAmount) : "—",
        },
    ];

    const panelH = Math.max(
        measurePanelHeight(doc, clientRows, colW),
        measurePanelHeight(doc, proposalRows, colW),
    );

    drawInfoPanel(doc, leftX, y, colW, "CLIENT DETAILS", clientRows, panelH);
    drawInfoPanel(doc, rightX, y, colW, "PROPOSAL INFORMATION", proposalRows, panelH);

    return y + panelH + 8;
}

function isTermsBlock(block: ContentBlock): boolean {
    if (block.type !== "heading") return false;
    return /terms?\s*&?\s*conditions?/i.test(block.title);
}

function drawHighlightBox(doc: PdfDoc, y: number, lines: string[]): number {
    const pageWidth = getPageWidth(doc);
    const contentWidth = pageWidth - PAGE_MARGIN * 2 - 8;
    const text = lines.map(stripInlineMarkdown).join("\n");
    const wrapped = doc.splitTextToSize(text, contentWidth);

    const boxH = wrapped.length * 4.2 + 10;
    const nextY = ensureSpace(doc, y, boxH + 4);

    doc.setFillColor(...HIGHLIGHT_FILL);
    doc.setDrawColor(BORDER, BORDER, BORDER);
    doc.rect(PAGE_MARGIN, nextY, pageWidth - PAGE_MARGIN * 2, boxH, "FD");

    doc.setFillColor(...ACCENT);
    doc.rect(PAGE_MARGIN, nextY, 3, boxH, "F");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(40, 40, 40);
    doc.text(wrapped, PAGE_MARGIN + 6, nextY + 7);

    return nextY + boxH + 6;
}

function drawBulletList(doc: PdfDoc, y: number, items: string[]): number {
    const pageWidth = getPageWidth(doc);
    const bulletX = PAGE_MARGIN + 3;
    const textX = PAGE_MARGIN + 8;
    const textWidth = pageWidth - textX - PAGE_MARGIN;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(50, 50, 50);

    for (const item of items) {
        const text = stripInlineMarkdown(item);
        const wrapped = doc.splitTextToSize(text, textWidth);
        y = ensureSpace(doc, y, wrapped.length * 4.2 + 2);
        doc.setFont("helvetica", "bold");
        doc.text("•", bulletX, y);
        doc.setFont("helvetica", "normal");
        doc.text(wrapped, textX, y);
        y += wrapped.length * 4.2 + 2;
    }

    return y + 2;
}

function drawDisplaySegments(doc: PdfDoc, y: number, segments: DisplaySegment[]): number {
    for (const segment of segments) {
        if (segment.type === "list") {
            y = drawBulletList(doc, y, segment.items);
            continue;
        }

        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(50, 50, 50);
        const text = segment.lines.map(stripInlineMarkdown).join("\n");
        const wrapped = doc.splitTextToSize(text, getPageWidth(doc) - PAGE_MARGIN * 2);
        y = ensureSpace(doc, y, wrapped.length * 4.2 + 2);
        doc.text(wrapped, PAGE_MARGIN, y);
        y += wrapped.length * 4.2 + 4;
    }

    return y;
}

function renderContentBlocks(
    doc: PdfDoc,
    autoTable: typeof import("jspdf-autotable").default,
    y: number,
    content: string,
): number {
    const blocks = parseProposalContent(content);
    if (blocks.length === 0) return y;

    let sectionNum = 0;

    for (const block of blocks) {
        if (block.type === "heading") {
            sectionNum += 1;
            const title = stripInlineMarkdown(block.title);
            y = ensureSpace(doc, y, 14);

            doc.setFont("helvetica", "bold");
            doc.setFontSize(10);
            doc.setTextColor(...ACCENT);
            doc.text(`${sectionNum}. ${title}`, PAGE_MARGIN, y);
            y += 6;

            if (block.lines.length > 0) {
                if (isTermsBlock(block)) {
                    y = drawHighlightBox(doc, y, block.lines);
                } else {
                    y = drawDisplaySegments(doc, y, groupLinesForDisplay(block.lines));
                }
            }
            continue;
        }

        if (block.type === "list") {
            y = drawBulletList(doc, y, block.items);
            continue;
        }

        if (block.type === "paragraph") {
            y = drawDisplaySegments(doc, y, groupLinesForDisplay(block.lines));
            continue;
        }

        if (block.type === "table") {
            y = ensureSpace(doc, y, 20);
            autoTable(doc, {
                startY: y,
                head: [block.header.map(stripInlineMarkdown)],
                body: block.rows.map((row) => row.map(stripInlineMarkdown)),
                theme: "grid",
                styles: {
                    fontSize: 8,
                    cellPadding: 2,
                    textColor: [40, 40, 40],
                    lineColor: [BORDER, BORDER, BORDER],
                    lineWidth: 0.2,
                },
                headStyles: {
                    fillColor: PRIMARY,
                    textColor: [255, 255, 255],
                    fontStyle: "bold",
                },
                alternateRowStyles: { fillColor: [252, 253, 255] },
                margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
                didDrawPage: (data) => {
                    if (data.cursor) {
                        y = data.cursor.y;
                    }
                },
            });
            const lastTable = (doc as PdfDoc & { lastAutoTable?: { finalY: number } }).lastAutoTable;
            y = (lastTable?.finalY ?? y) + 6;
        }
    }

    return y;
}

function drawClosing(doc: PdfDoc, y: number): number {
    y = ensureSpace(doc, y, 24);
    drawHr(doc, y);
    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    doc.text("Thanks, We are waiting for your positive response...", PAGE_MARGIN, y);
    return y + 6;
}

export async function downloadProposalPdf(proposal: Proposal): Promise<void> {
    const [{ jsPDF }, autoTableModule, logo] = await Promise.all([
        import("jspdf"),
        import("jspdf-autotable"),
        loadLogoAsset(),
    ]);
    const autoTable = autoTableModule.default;
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

    let y = drawHeader(doc, logo);
    y = drawTitleBand(doc, y, proposal.projectTitle);
    y = drawDualInfoPanels(doc, y, proposal);

    if (proposal.content.trim()) {
        y = renderContentBlocks(doc, autoTable, y, proposal.content);
    }

    y = drawClosing(doc, y);

    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        drawPageFooter(doc, i, totalPages);
    }

    const safeName = proposal.proposalNumber.replace(/[^\w-]+/g, "_");
    doc.save(`Proposal-${safeName}.pdf`);
}
