
CREATE TABLE IF NOT EXISTS navbar_content (
    id INT AUTO_INCREMENT PRIMARY KEY,
    logo_url VARCHAR(255) DEFAULT '/logo.png',
    brand_title VARCHAR(100) DEFAULT 'VIROS',
    brand_subtitle VARCHAR(100) DEFAULT 'Entrepreneurs',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
