-- Admin HRMS employees (directory + full registration payload)

CREATE TABLE IF NOT EXISTS admin_employees (
    id INT AUTO_INCREMENT PRIMARY KEY,
    employee_id VARCHAR(64) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    gender VARCHAR(32) NULL,
    date_of_birth DATE NULL,
    marital_status VARCHAR(32) NULL,
    blood_group VARCHAR(16) NULL,
    nationality VARCHAR(128) NULL,
    religion VARCHAR(128) NULL,
    category VARCHAR(128) NULL,
    personal_mobile VARCHAR(32) NULL,
    official_mobile VARCHAR(32) NULL,
    personal_email VARCHAR(255) NULL,
    official_email VARCHAR(255) NULL,
    current_address TEXT NULL,
    permanent_address TEXT NULL,
    parent_name VARCHAR(255) NULL,
    parent_mobile VARCHAR(32) NULL,
    parent_occupation VARCHAR(255) NULL,
    guardian_relation VARCHAR(128) NULL,
    higher_education_qualification VARCHAR(64) NULL,
    higher_education_course_name VARCHAR(255) NULL,
    higher_education_institution VARCHAR(255) NULL,
    higher_education_passing_year VARCHAR(16) NULL,
    higher_education_cgpa VARCHAR(32) NULL,
    higher_education_specialization VARCHAR(255) NULL,
    department VARCHAR(255) NULL,
    designation VARCHAR(255) NULL,
    employee_type VARCHAR(64) NULL,
    employment_category VARCHAR(64) NULL,
    joining_date DATE NULL,
    probation_period VARCHAR(64) NULL,
    work_location VARCHAR(255) NULL,
    branch_name VARCHAR(255) NULL,
    reporting_manager VARCHAR(255) NULL,
    employee_status VARCHAR(32) NOT NULL DEFAULT 'Active',
    previous_company_name VARCHAR(255) NULL,
    previous_designation VARCHAR(255) NULL,
    previous_salary VARCHAR(64) NULL,
    work_experience_years VARCHAR(32) NULL,
    previous_joining_date DATE NULL,
    previous_relieving_date DATE NULL,
    reason_for_leaving TEXT NULL,
    reference_person_name VARCHAR(255) NULL,
    reference_contact_number VARCHAR(32) NULL,
    aadhaar_number VARCHAR(32) NULL,
    pan_number VARCHAR(32) NULL,
    passport_number VARCHAR(64) NULL,
    voter_id_number VARCHAR(64) NULL,
    driving_license_number VARCHAR(64) NULL,
    uan_number VARCHAR(64) NULL,
    esic_number VARCHAR(64) NULL,
    pf_number VARCHAR(64) NULL,
    bank_name VARCHAR(255) NULL,
    bank_branch_name VARCHAR(255) NULL,
    account_holder_name VARCHAR(255) NULL,
    account_number VARCHAR(64) NULL,
    ifsc_code VARCHAR(32) NULL,
    upi_id VARCHAR(128) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_admin_employees_employee_id (employee_id)
);
