const DEFAULT_EMAIL = "sales@virosentrepreneurs.com";
const DEFAULT_PHONE = "+91-987102-9141";

type GeneratedDocumentFooterProps = {
    kind?: "letter" | "offer";
    email?: string;
    phone?: string;
    pageNum?: number;
    totalPages?: number;
};

export default function GeneratedDocumentFooter({
    kind = "letter",
    email = DEFAULT_EMAIL,
    phone = DEFAULT_PHONE,
    pageNum = 1,
    totalPages = 1,
}: GeneratedDocumentFooterProps) {
    const banner =
        kind === "offer"
            ? "*** This offer letter is generated by the system ***"
            : "*** This letter is generated by the system ***";

    return (
        <footer className="mt-10 border-t border-gray-200 px-8 py-5 text-center sm:px-12">
            <p className="text-xs italic text-[#06b6d4]">{banner}</p>
            <p className="mt-2 text-[11px] text-gray-500">
                For any queries, contact us at {email} | {phone}
            </p>
            <p className="mt-2 text-xs text-gray-600">
                Page {pageNum} of {totalPages}
            </p>
        </footer>
    );
}
